volumes:
  db_data:

services:
  db:
    image: postgres:15
    container_name: foojidoo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food_delivery
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d food_delivery"]
      interval: 10s
      timeout: 5s
      retries: 5
